# Generated by Django 4.2.1 on 2023-06-09 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
