# Generated by Django 4.2.1 on 2023-06-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_paymentmethod_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
