# Generated by Django 4.2.1 on 2023-06-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
