# Generated by Django 4.2.1 on 2023-06-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_rename_categories_category_delete_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bid_price',
        ),
    ]
