# Generated by Django 4.2.1 on 2023-07-12 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 19, 31, 18, 110435)),
        ),
    ]
