# Generated by Django 3.2.3 on 2023-07-18 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_product_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Description',
        ),
        migrations.AddField(
            model_name='product',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 18, 19, 20, 23, 572080), null=True),
        ),
    ]
