# Generated by Django 3.2.3 on 2023-07-18 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20230718_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 18, 20, 7, 10, 932791), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
