# Generated by Django 4.2.1 on 2023-06-07 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0002_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
