# Generated by Django 4.2.1 on 2023-06-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_user'),
        ('Bidding', '0006_remove_cart_product_cart_bid_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='bid',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
