# Generated by Django 4.2.1 on 2023-06-17 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0008_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
