# Generated by Django 4.2.1 on 2023-07-12 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0021_alter_bid_datetime_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 12, 19, 47, 15, 796420)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 12, 19, 47, 15, 797445)),
        ),
    ]
