# Generated by Django 4.2.1 on 2023-07-13 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0024_alter_bid_datetime_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 13, 12, 34, 41, 749310)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 13, 12, 34, 41, 749310)),
        ),
    ]
