# Generated by Django 4.2.1 on 2023-07-13 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0025_remove_order_address_remove_order_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 13, 16, 19, 14, 670518)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 13, 16, 19, 14, 670518)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 13, 16, 19, 14, 671516)),
        ),
    ]
