# Generated by Django 4.2.1 on 2023-07-13 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0026_watchlist_datetime_alter_bid_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], default='Due', max_length=255),
        ),
        migrations.AlterField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 13, 16, 55, 19, 13504)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 13, 16, 55, 19, 14500)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 13, 16, 55, 19, 13504)),
        ),
    ]
