# Generated by Django 3.2.3 on 2023-07-18 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0029_alter_bid_datetime_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 18, 19, 2, 26, 935114)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 18, 19, 2, 26, 950735)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 18, 19, 2, 26, 935114)),
        ),
    ]
