# Generated by Django 4.2.1 on 2023-07-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Ads'},
        ),
    ]
